---

- name: Ensure desired datacenters exist as required.
  local_action:
    module: vmware_datacenter
    hostname: "{{ cornerstone_vcenter_hostname }}"
    username: "{{ cornerstone_vcenter_username }}"
    password: "{{ cornerstone_vcenter_password }}"
    datacenter_name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ from_template.cornerstone_vmware_datacenter }}"

- name: Ensure desired clusters exist as desired.
  local_action:
    module: vmware_cluster
    hostname: "{{ cornerstone_vcenter_hostname }}"
    username: "{{ cornerstone_vcenter_username }}"
    password: "{{ cornerstone_vcenter_password }}"
    datacenter_name: "{{ item.datacenter }}"
    cluster_name: "{{ item.name }}"
    enable_ha:  "{{ item.ha_bool }}"
    enable_drs: "{{ item.drs_bool }}"
    enable_vsan: "{{ item.vsan_bool }}"
    state:  "{{ item.state }}"
  with_items: "{{ from_template.cornerstone_vmware_cluster }}"