---
# tasks file for cornerstone

#
# -----------------------------------------------------------------------------
# Common Tasks
# -----------------------------------------------------------------------------
#
- include: common-{{ cornerstone_platform }}.yml
  tags: [common, "{{ cornerstone_platform }}"]


#
# -----------------------------------------------------------------------------
# Network Tasks
# -----------------------------------------------------------------------------
#
- include: network-{{ cornerstone_platform }}.yml
  tags: [network, "{{ cornerstone_platform }}"]

#
# -----------------------------------------------------------------------------
# Virtual Machine Tasks
# -----------------------------------------------------------------------------
#

  #- name: Build vms based on dict 
  #    
  #    shell: "virt-customize --ssh-inject root:file:/root/.ssh/id_rsa.pub --selinux-relabel -d {{ item.key }}.{{ domain_name }}"
  #  with_dict: "{{ guests }}"

- include: vm-{{ cornerstone_platform }}.yml
  tags: [vm, "{{ cornerstone_platform }}"]

#
# -----------------------------------------------------------------------------
# Discover IP Address Tasks
# -----------------------------------------------------------------------------
#
- include: discover-ip-{{ cornerstone_platform }}.yml
  tags: ["{{ cornerstone_platform }}"]

# EOF
